name: build and push

on:
  workflow_dispatch:

  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out
        uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        run: make prod

      - name: Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://autodok.cars10k.de/update'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "authorization": "${{ secrets.AUTODOK_API_KEY }}"}'
          data: '{"container": "elasticvue_com-react", "image": "ghcr.io/cars10/elasticvue_com", "registry": {"username": "${{ secrets.DOCKER_USERNAME }}", "password": "${{ secrets.DOCKER_PASSWORD }}", "serveraddress": "ghrc.io"}}'
